/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_erickcarrasco;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileFilter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author erick
 */
public class Principal_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Panel
     */
    public Principal_Panel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_loggedin = new javax.swing.JDialog();
        tab_loggedin = new javax.swing.JTabbedPane();
        jt_inicio = new javax.swing.JPanel();
        jl_Nombre = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lb_icon2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_log = new javax.swing.JTextArea();
        jp_add = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_personas_actuales = new javax.swing.JList();
        jLabel16 = new javax.swing.JLabel();
        jb_mover_lista = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_amigos_actuales = new javax.swing.JList();
        Personas = new javax.swing.JLabel();
        jp_infopeople = new javax.swing.JPanel();
        cb_users = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        tf_edad1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lb_icon3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ta_infoPersona_ip = new javax.swing.JTextArea();
        jp_allpeopleinfo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlist_personas = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_jlist1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jb_mostrar_data = new javax.swing.JButton();
        block = new javax.swing.JPanel();
        jp_dates = new javax.swing.JPanel();
        intereses = new javax.swing.JPanel();
        mensaje = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        lista_mensajes_recibidos = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        lista_amigos_mensajes = new javax.swing.JList();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        texto_mensaje = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        mensaje_leer = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_registro_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        js_edad_register = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        tf_username_register = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pf_pass_register = new javax.swing.JPasswordField();
        lb_foto = new javax.swing.JLabel();
        jb_seleccionar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_premium_register = new javax.swing.JComboBox();
        jb_register = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cb_sex_register = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcione = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_intereses = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_login_username = new javax.swing.JTextField();
        jb_login_log = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pf_pass_login = new javax.swing.JPasswordField();

        tab_loggedin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_loggedinStateChanged(evt);
            }
        });

        jl_Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Fotografia");

        lb_icon2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setText("Descripcione");

        ta_log.setEditable(false);
        ta_log.setColumns(20);
        ta_log.setRows(5);
        jScrollPane3.setViewportView(ta_log);

        javax.swing.GroupLayout jt_inicioLayout = new javax.swing.GroupLayout(jt_inicio);
        jt_inicio.setLayout(jt_inicioLayout);
        jt_inicioLayout.setHorizontalGroup(
            jt_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jt_inicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jt_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jt_inicioLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(lb_icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jl_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jt_inicioLayout.setVerticalGroup(
            jt_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jt_inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jt_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(lb_icon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        tab_loggedin.addTab("Inicio", jt_inicio);

        jl_personas_actuales.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jl_personas_actuales);

        jLabel16.setText("Amigos");

        jb_mover_lista.setText("->");
        jb_mover_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_mover_listaMouseClicked(evt);
            }
        });

        jl_amigos_actuales.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_amigos_actuales);

        Personas.setText("Persona");

        javax.swing.GroupLayout jp_addLayout = new javax.swing.GroupLayout(jp_add);
        jp_add.setLayout(jp_addLayout);
        jp_addLayout.setHorizontalGroup(
            jp_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jp_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_addLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jb_mover_lista))
                    .addComponent(Personas))
                .addGap(36, 36, 36)
                .addGroup(jp_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jp_addLayout.setVerticalGroup(
            jp_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_addLayout.createSequentialGroup()
                .addGroup(jp_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_addLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jb_mover_lista))
                    .addGroup(jp_addLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Personas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        tab_loggedin.addTab("Agregar Amigos", jp_add);

        cb_users.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_usersItemStateChanged(evt);
            }
        });

        jLabel17.setText("Nombre");

        tf_nombre1.setEditable(false);

        tf_edad1.setEditable(false);

        jLabel18.setText("Edad");

        lb_icon3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel19.setText("Fotografia");

        jLabel20.setText("Descripcion");

        ta_infoPersona_ip.setEditable(false);
        ta_infoPersona_ip.setColumns(20);
        ta_infoPersona_ip.setRows(5);
        jScrollPane8.setViewportView(ta_infoPersona_ip);

        javax.swing.GroupLayout jp_infopeopleLayout = new javax.swing.GroupLayout(jp_infopeople);
        jp_infopeople.setLayout(jp_infopeopleLayout);
        jp_infopeopleLayout.setHorizontalGroup(
            jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_infopeopleLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_users, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_infopeopleLayout.createSequentialGroup()
                        .addGroup(jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_infopeopleLayout.createSequentialGroup()
                                .addGroup(jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombre1)
                                    .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_infopeopleLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(lb_icon3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82)
                        .addGroup(jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jp_infopeopleLayout.setVerticalGroup(
            jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_infopeopleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_infopeopleLayout.createSequentialGroup()
                        .addGroup(jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_infopeopleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(lb_icon3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(87, 87, 87))
                    .addGroup(jp_infopeopleLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tab_loggedin.addTab("Info Personas", jp_infopeople);

        jlist_personas.setModel(new DefaultListModel());
        jlist_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlist_personasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jlist_personas);

        ta_jlist1.setColumns(20);
        ta_jlist1.setRows(5);
        jScrollPane5.setViewportView(ta_jlist1);

        jLabel15.setText("Informacion");

        jb_mostrar_data.setText("->");
        jb_mostrar_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_mostrar_dataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_allpeopleinfoLayout = new javax.swing.GroupLayout(jp_allpeopleinfo);
        jp_allpeopleinfo.setLayout(jp_allpeopleinfoLayout);
        jp_allpeopleinfoLayout.setHorizontalGroup(
            jp_allpeopleinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_allpeopleinfoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_mostrar_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_allpeopleinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jp_allpeopleinfoLayout.setVerticalGroup(
            jp_allpeopleinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_allpeopleinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_allpeopleinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_allpeopleinfoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGroup(jp_allpeopleinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_allpeopleinfoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_allpeopleinfoLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jb_mostrar_data)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tab_loggedin.addTab("Lista de personas", jp_allpeopleinfo);

        javax.swing.GroupLayout blockLayout = new javax.swing.GroupLayout(block);
        block.setLayout(blockLayout);
        blockLayout.setHorizontalGroup(
            blockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        blockLayout.setVerticalGroup(
            blockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        tab_loggedin.addTab("Bloquear ", block);

        javax.swing.GroupLayout jp_datesLayout = new javax.swing.GroupLayout(jp_dates);
        jp_dates.setLayout(jp_datesLayout);
        jp_datesLayout.setHorizontalGroup(
            jp_datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        jp_datesLayout.setVerticalGroup(
            jp_datesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        tab_loggedin.addTab("Calendario", jp_dates);

        javax.swing.GroupLayout interesesLayout = new javax.swing.GroupLayout(intereses);
        intereses.setLayout(interesesLayout);
        interesesLayout.setHorizontalGroup(
            interesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        interesesLayout.setVerticalGroup(
            interesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        tab_loggedin.addTab("Intereses", intereses);

        jLabel21.setText("Mis mensajes");

        lista_mensajes_recibidos.setModel(new DefaultListModel());
        jScrollPane9.setViewportView(lista_mensajes_recibidos);

        lista_amigos_mensajes.setModel(new DefaultListModel());
        jScrollPane10.setViewportView(lista_amigos_mensajes);

        jLabel22.setText("Amigos");

        texto_mensaje.setColumns(20);
        texto_mensaje.setRows(5);
        jScrollPane11.setViewportView(texto_mensaje);

        jLabel23.setText("Mensaje");

        jButton1.setText("Enviar");

        mensaje_leer.setColumns(20);
        mensaje_leer.setRows(5);
        jScrollPane12.setViewportView(mensaje_leer);

        javax.swing.GroupLayout mensajeLayout = new javax.swing.GroupLayout(mensaje);
        mensaje.setLayout(mensajeLayout);
        mensajeLayout.setHorizontalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jButton1))
                .addGap(59, 59, 59)
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        mensajeLayout.setVerticalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mensajeLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mensajeLayout.createSequentialGroup()
                        .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jButton1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        tab_loggedin.addTab("Mensajes", mensaje);

        javax.swing.GroupLayout jd_loggedinLayout = new javax.swing.GroupLayout(jd_loggedin.getContentPane());
        jd_loggedin.getContentPane().setLayout(jd_loggedinLayout);
        jd_loggedinLayout.setHorizontalGroup(
            jd_loggedinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loggedinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_loggedin, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_loggedinLayout.setVerticalGroup(
            jd_loggedinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loggedinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_loggedin, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Edad");

        jLabel3.setText("UserName");

        jLabel4.setText("Password");

        lb_foto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jb_seleccionar.setText("Seleccionar");
        jb_seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_seleccionarMouseClicked(evt);
            }
        });

        jLabel5.setText("Imagen");

        jLabel6.setText("Premium");

        cb_premium_register.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));

        jb_register.setText("Registro");
        jb_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registerMouseClicked(evt);
            }
        });

        jLabel7.setText("Sexo");

        cb_sex_register.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        jLabel11.setText("Descripcione");

        ta_descripcione.setColumns(20);
        ta_descripcione.setRows(5);
        jScrollPane1.setViewportView(ta_descripcione);

        jLabel12.setText("Intereses");

        ta_intereses.setColumns(20);
        ta_intereses.setRows(5);
        jScrollPane2.setViewportView(ta_intereses);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_registro_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_edad_register, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_username_register))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf_pass_register)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_premium_register, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_seleccionar)
                    .addComponent(jLabel7))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_register)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(cb_sex_register, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_registro_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(js_edad_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_username_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pf_pass_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_seleccionar)
                            .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_premium_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cb_sex_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(38, 38, 38)
                        .addComponent(jb_register))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registro", jPanel1);

        jLabel8.setFont(new java.awt.Font("Eurostile Extended", 3, 24)); // NOI18N
        jLabel8.setText("LOG IN");

        jLabel9.setText("User Name:");

        jb_login_log.setText("Log in");
        jb_login_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_login_logMouseClicked(evt);
            }
        });

        jLabel10.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_login_log)
                            .addComponent(tf_login_username)
                            .addComponent(pf_pass_login, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pf_pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(jb_login_log)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Log in", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_seleccionarMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes",
            "png", "jpg", "jpeg");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op== JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(
                archivo.getPath()).getScaledInstance(100, 100, 0);
            this.lb_foto.setIcon(new ImageIcon(img));

        }
    }//GEN-LAST:event_jb_seleccionarMouseClicked

    private void jb_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registerMouseClicked
        // TODO add your handling code here:
        aP.cargarArchivo();
        ArrayList <String> temp1 = new ArrayList();
        ArrayList <String> temp2 = new ArrayList();
        ArrayList <String> temp3 = new ArrayList();
        String nombre = tf_registro_nombre.getText();
        String username = tf_username_register.getText();
        String password = pf_pass_register.getText();
        String descripcione = ta_descripcione.getText();
        boolean validador1=true, validador2=true, validador3=true;
        int c=0;
        for (Persona p : aP.getListaPersonas()) {
            String user = aP.getListaPersonas().get(c).getUser();
            if (user.equals(username)) {
                validador1=false;
            }
            c++;
        }
        int edad = (Integer)js_edad_register.getValue();
        if (edad<18) {
            validador2 = false;
        }
        String sexo = cb_sex_register.getSelectedItem().toString();
        String [] intereses = ta_intereses.getText().split(",");
        if (intereses.length<9) {
            validador3=false;
        }
        String premium = cb_premium_register.getSelectedItem().toString();
        
        if (validador3 == true && validador2 == true && validador1 == true) {
            Persona p = new Persona(nombre, edad, lb_foto.getIcon(), username, password, sexo, premium, descripcione);
            
            for (int i = 0; i < intereses.length; i++) {
                temp1.add(intereses[i]);
            }
            p.setIntereses(temp1);
            
            aP.setPersona(p);
            aP.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            tf_registro_nombre.setText("");
            tf_username_register.setText("");
            ta_descripcione.setText("");
            ta_intereses.setText("");
        }else{
            if (validador1==false) {
                JOptionPane.showMessageDialog(this, "Usuario ya ocupado");
                tf_username_register.setText("");
            }
            if (validador2 == false) {
                JOptionPane.showMessageDialog(this, "Edad es incorrecta, debe ser mayor de 18");
            }
            if (validador3 == false) {
                JOptionPane.showMessageDialog(this, "Intereses restantes..");
            }
        }
        
        
    }//GEN-LAST:event_jb_registerMouseClicked

    private void jb_login_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_login_logMouseClicked
        // TODO add your handling code here:
        aP.cargarArchivo();
        String uservalidate = tf_login_username.getText();
        String pass_validate = pf_pass_login.getText();
        int c=0;
        String pass;
        String user_auth="";
        int count=0;
        for (Persona p : aP.getListaPersonas()) {
            String user = aP.getListaPersonas().get(c).getUser();
            
            if (user.equals(uservalidate)) {
                user_auth= user;
                count = c;
                countglobal = count;
            }
            c++;
        }
        
         pass = aP.getListaPersonas().get(count).getPassword();
        if (pass_validate.equals(pass) && uservalidate.equals(user_auth)) {
            JOptionPane.showMessageDialog(this, "Ingreso exitosamente");
            jl_Nombre.setText(aP.getListaPersonas().get(count).getNombre());
            lb_icon2.setIcon(aP.getListaPersonas().get(count).getFotografia());
            ta_log.setText(aP.getListaPersonas().get(count).getDescripzione());
            jd_loggedin.setModal(true);
            jd_loggedin.pack();
            jd_loggedin.setLocationRelativeTo(this);
            jd_loggedin.setVisible(true);
            tf_login_username.setText("");
            pf_pass_login.setText("");
            
        }else{
            JOptionPane.showMessageDialog(this, "Incorrect data");
            pf_pass_login.setText("");
        }
    }//GEN-LAST:event_jb_login_logMouseClicked

    private void tab_loggedinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab_loggedinStateChanged
        // TODO add your handling code here:
        if (tab_loggedin.getSelectedIndex()==2) {
            aP.cargarArchivo();
            DefaultComboBoxModel modelo
                    = new DefaultComboBoxModel(
                            aP.getListaPersonas().toArray());
            cb_users.setModel(modelo);
        }
        if (tab_loggedin.getSelectedIndex()==3) {
     
            DefaultListModel m = (DefaultListModel) jlist_personas.getModel();
            if (m.isEmpty()) {
                int c = 0;
                for (Persona p : aP.getListaPersonas()) {
                    if (c != countglobal) {
                        m.addElement(aP.getListaPersonas().get(c));
                    }
                    c++;
                }
            }else{
                m.removeAllElements();
                int c = 0;
                for (Persona p : aP.getListaPersonas()) {
                    if (c != countglobal) {
                        m.addElement(aP.getListaPersonas().get(c));
                    }
                    c++;
                }
            }

        }
        if (tab_loggedin.getSelectedIndex() == 1) {
            aP.cargarArchivo();
            DefaultListModel n = (DefaultListModel) jl_personas_actuales.getModel();
            if (n.isEmpty()) {
                int c = 0;
                for (Persona p : aP.getListaPersonas()) {
                    if (c != countglobal) {
                        n.addElement(aP.getListaPersonas().get(c));
                    }
                    c++;
                }
            } else {
                n.removeAllElements();
                int c = 0;
                for (Persona p : aP.getListaPersonas()) {
                    if (c != countglobal) {
                        n.addElement(aP.getListaPersonas().get(c));
                    }
                    c++;
                }
            }
            
            DefaultListModel m2 = (DefaultListModel) jl_amigos_actuales.getModel();
            if (m2.isEmpty()) {
                String user = aP.getListaPersonas().get(countglobal).getUser();
                int c = 0;
                for (Persona t : aP.getListaPersonas()) {
                    String uservalidate = aP.getListaPersonas().get(c).getUser();
                    if (user.equals(uservalidate)) {
                        for (int i = 0; i < t.getAmigos().size(); i++) {
                            m2.addElement(t.getAmigos().get(i));
                        }
                    }
                    c++;
                }
                //jl_amigos_actuales.setModel(m2);
            } else {
                m2.removeAllElements();
                String user = aP.getListaPersonas().get(countglobal).getUser();
                int c = 0;
                for (Persona t : aP.getListaPersonas()) {
                    String uservalidate = aP.getListaPersonas().get(c).getUser();
                    if (user.equals(uservalidate)) {
                        for (int i = 0; i < t.getAmigos().size(); i++) {
                            m2.addElement(t.getAmigos().get(i));
                        }
                    }
                    c++;
                }
            }

        }
        if (tab_loggedin.getSelectedIndex() == 7) {
            aP.cargarArchivo();
            DefaultListModel m = (DefaultListModel) lista_amigos_mensajes.getModel();
            if (m.isEmpty()) {
                String user = aP.getListaPersonas().get(countglobal).getUser();
                int c = 0;
                for (Persona t : aP.getListaPersonas()) {
                    String uservalidate = aP.getListaPersonas().get(c).getUser();
                    if (user.equals(uservalidate)) {
                        for (int i = 0; i < t.getAmigos().size(); i++) {
                            m.addElement(t.getAmigos().get(i));
                        }
                    }
                    c++;
                }
                //jl_amigos_actuales.setModel(m2);
            } else {
                m.removeAllElements();
                String user = aP.getListaPersonas().get(countglobal).getUser();
                int c = 0;
                for (Persona t : aP.getListaPersonas()) {
                    String uservalidate = aP.getListaPersonas().get(c).getUser();
                    if (user.equals(uservalidate)) {
                        for (int i = 0; i < t.getAmigos().size(); i++) {
                            m.addElement(t.getAmigos().get(i));
                        }
                    }
                    c++;
                }
            }
            DefaultListModel m2 = (DefaultListModel) lista_mensajes_recibidos.getModel();
            
            if((aP.getListaPersonas().get(countglobal).getMensajes())==null){
                ArrayList temp = new ArrayList();
                aP.getListaPersonas().get(countglobal).setMensajes(temp);
                
                String user = aP.getListaPersonas().get(countglobal).getUser();
                int c = 0;
                for (Persona t : aP.getListaPersonas()) {
                    String uservalidate = aP.getListaPersonas().get(c).getUser();
                    if (user.equals(uservalidate)) {
                        for (int i = 0; i < t.getMensajes().size(); i++) {
                            m2.addElement(t.getMensajes().get(i));
                        }
                    }
                    c++;
                }
                aP.escribirArchivo();
            }else{
                m2.removeAllElements();
                
                
                String user = aP.getListaPersonas().get(countglobal).getUser();
                int c = 0;
                for (Persona t : aP.getListaPersonas()) {
                    String uservalidate = aP.getListaPersonas().get(c).getUser();
                    if (user.equals(uservalidate)) {
                        for (int i = 0; i < t.getMensajes().size(); i++) {
                            m2.addElement(t.getMensajes().get(i));
                        }
                    }
                    c++;
                }
            }
        }

    }//GEN-LAST:event_tab_loggedinStateChanged

    private void jlist_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlist_personasMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jlist_personasMouseClicked

    private void jb_mostrar_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_mostrar_dataMouseClicked
        // TODO add your handling code here:
        if (jlist_personas.getSelectedIndex() >= 0) {
            ta_jlist1.setText("");
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jlist_personas.getModel();
            String nombre=((Persona) modeloLISTA.get(
                    jlist_personas.getSelectedIndex())).getNombre();
            String descripcion = ((Persona) modeloLISTA.get(
                    jlist_personas.getSelectedIndex())).getDescripzione();
            int age = ((Persona) modeloLISTA.get(
                    jlist_personas.getSelectedIndex())).getEdad();
            
           String intereses = ((Persona) modeloLISTA.get(
                        jlist_personas.getSelectedIndex())).getIntereses().toString();
            
            ta_jlist1.append("Nombre: "+nombre+"\n"
                    + "Descripcion: "+descripcion+"\n"
                    + "Edad: "+age+"\n"
                    + "Intereses: "+"\n"
                    + intereses + "\n"
                    );

        }
    }//GEN-LAST:event_jb_mostrar_dataMouseClicked

    private void cb_usersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_usersItemStateChanged
        // TODO add your handling code here:
        Persona temp 
                = (Persona) cb_users.getSelectedItem();
        if (temp !=null) {
            tf_nombre1.setText(temp.getNombre());
            tf_edad1.setText(Integer.toString(temp.getEdad()));
            lb_icon3.setIcon(temp.getFotografia());
            ta_infoPersona_ip.setText(temp.getDescripzione());
        }
    }//GEN-LAST:event_cb_usersItemStateChanged

    private void jb_mover_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_mover_listaMouseClicked
        // TODO add your handling code here:
        try {
            aP.cargarArchivo();
            if (jl_personas_actuales.getSelectedIndex() >= 0) {
                DefaultListModel m = (DefaultListModel) jl_personas_actuales.getModel();
                DefaultListModel m2 = (DefaultListModel) jl_amigos_actuales.getModel();
                int c=0;
                ArrayList<Persona> tempam = new ArrayList();
                
                String user=aP.getListaPersonas().get(countglobal).getUser();
                for (Persona t : aP.getListaPersonas()) {
                    String uservalidate=aP.getListaPersonas().get(c).getUser();
                    if (user.equals(uservalidate)) {
                        t.getAmigos().add((Persona) m.get(jl_personas_actuales.getSelectedIndex()));
                        m2.addElement(t.getAmigos().get(t.getAmigos().size() - 1));
                        tempam.add(((Persona) m.get(jl_personas_actuales.getSelectedIndex())));
                    }
                    c++;
                }
                jl_amigos_actuales.setModel(m2);
                m.remove(jl_personas_actuales.getSelectedIndex());
                jl_personas_actuales.setModel(m);
                aP.getListaPersonas().get(countglobal).setAmigos(tempam);
                aP.escribirArchivo();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_mover_listaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Personas;
    private javax.swing.JPanel block;
    private javax.swing.JComboBox cb_premium_register;
    private javax.swing.JComboBox cb_sex_register;
    private javax.swing.JComboBox cb_users;
    private javax.swing.JPanel intereses;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_login_log;
    private javax.swing.JButton jb_mostrar_data;
    private javax.swing.JButton jb_mover_lista;
    private javax.swing.JButton jb_register;
    private javax.swing.JButton jb_seleccionar;
    private javax.swing.JDialog jd_loggedin;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JList jl_amigos_actuales;
    private javax.swing.JList jl_personas_actuales;
    private javax.swing.JList jlist_personas;
    private javax.swing.JPanel jp_add;
    private javax.swing.JPanel jp_allpeopleinfo;
    private javax.swing.JPanel jp_dates;
    private javax.swing.JPanel jp_infopeople;
    private javax.swing.JSpinner js_edad_register;
    private javax.swing.JPanel jt_inicio;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lb_icon2;
    private javax.swing.JLabel lb_icon3;
    private javax.swing.JList lista_amigos_mensajes;
    private javax.swing.JList lista_mensajes_recibidos;
    private javax.swing.JPanel mensaje;
    private javax.swing.JTextArea mensaje_leer;
    private javax.swing.JPasswordField pf_pass_login;
    private javax.swing.JPasswordField pf_pass_register;
    private javax.swing.JTextArea ta_descripcione;
    private javax.swing.JTextArea ta_infoPersona_ip;
    private javax.swing.JTextArea ta_intereses;
    private javax.swing.JTextArea ta_jlist1;
    private javax.swing.JTextArea ta_log;
    private javax.swing.JTabbedPane tab_loggedin;
    private javax.swing.JTextArea texto_mensaje;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_login_username;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_registro_nombre;
    private javax.swing.JTextField tf_username_register;
    // End of variables declaration//GEN-END:variables
    adminPersonas aP = new adminPersonas("./Usuarios.lbp");
    DefaultMutableTreeNode nodo_seleccionado;
    Persona persona_seleccionada;
    int countglobal;
}
